(1.0,
  SimpleClassificationPipeline(
    {'balancing:strategy': 'weighting', 
     'classifier:__choice__': 'sgd',
      'data_preprocessing:categorical_transformer:categorical_encoding:__choice__': 'one_hot_encoding',
      'data_preprocessing:categorical_transformer:category_coalescence:__choice__': 'minority_coalescer',
      'data_preprocessing:numerical_transformer:imputation:strategy': 'median',
      'data_preprocessing:numerical_transformer:rescaling:__choice__': 'quantile_transformer',
      'feature_preprocessor:__choice__': 'fast_ica', 
      'classifier:sgd:alpha': 0.031866765830749336,
      'classifier:sgd:average': 'False', 
      'classifier:sgd:fit_intercept': 'True', 
      'classifier:sgd:learning_rate': 'constant',
      'classifier:sgd:loss': 'squared_hinge', 
      'classifier:sgd:penalty': 'l2', 
      'classifier:sgd:tol': 1.0191769708510488e-05, 
      'data_preprocessing:categorical_transformer:category_coalescence:minority_coalescer:minimum_fraction': 0.00011709809225840547, 
      'data_preprocessing:numerical_transformer:rescaling:quantile_transformer:n_quantiles': 1772, 
      'data_preprocessing:numerical_transformer:rescaling:quantile_transformer:output_distribution': 'uniform', 
      'feature_preprocessor:fast_ica:algorithm': 'parallel', 'feature_preprocessor:fast_ica:fun': 'exp', 
      'feature_preprocessor:fast_ica:whiten': 'False', 'classifier:sgd:eta0': 0.0028168181617106067},
  dataset_properties={
    'task': 1,
    'sparse': False,
    'multilabel': False,
    'multiclass': False,
    'target_type': 'classification',
    'signed': False}))]
